#!/bin/sh

VERSION=2.4.11

cd $HOME

curl -LO https://github.com/github/gollum/archive/v$VERSION.tar.gz
tar xzf v$VERSION.tar.gz -C $HOME/tmp
rm $HOME/tmp/gollum-$VERSION/Gemfile $HOME/tmp/gollum-$VERSION/Gemfile.lock $HOME/tmp/gollum-$VERSION/config.ru
cp -a $HOME/tmp/gollum-$VERSION/* $HOME/current/
rm -rf $HOME/tmp/*

ln -s $HOME/current/lib/gollum/frontend/public/gollum $HOME/current/public

git init $HOME/wiki
cd $HOME/wiki
cp $HOME/current/*.md .
git add .
git commit -m 'Initial commit'

/etc/init.d/app restart
